DDD_REGIAO = {
    11: {"regiao": "São Paulo", "uf": "SP"},
    12: {"regiao": "São José dos Campos", "uf": "SP"},
    13: {"regiao": "Santos", "uf": "SP"},
    14: {"regiao": "Bauru", "uf": "SP"},
    15: {"regiao": "Sorocaba", "uf": "SP"},
    16: {"regiao": "Ribeirão Preto", "uf": "SP"},
    17: {"regiao": "São José do Rio Preto", "uf": "SP"},
    18: {"regiao": "Presidente Prudente", "uf": "SP"},
    19: {"regiao": "Campinas", "uf": "SP"},
    19: {"regiao": "Campinas", "uf": "SP"},
    21: {"regiao": "Rio de Janeiro", "uf": "RJ"},
    22: {"regiao": "Campos dos Goytacazes", "uf": "RJ"},
    24: {"regiao": "Volta Redonda", "uf": "RJ"},
    27: {"regiao": "Vitória / Vila Velha", "uf": "ES"},
    28: {"regiao": "Cachoeiro de Itapemirim", "uf": "ES"},
    31: {"regiao": "Belo Horizonte", "uf": "MG"},
    32: {"regiao": "Juiz de Fora", "uf": "MG"},
    33: {"regiao": "Governador Valadares", "uf": "MG"},
    34: {"regiao": "Uberlândia", "uf": "MG"},
    35: {"regiao": "Poços de Caldas", "uf": "MG"},
    37: {"regiao": "Divinópolis", "uf": "MG"},
    38: {"regiao": "Montes Claros", "uf": "MG"},
    41: {"regiao": "Curitiba", "uf": "PR"},
    42: {"regiao": "Ponta Grossa", "uf": "PR"},
    43: {"regiao": "Londrina", "uf": "PR"},
    44: {"regiao": "Maringá", "uf": "PR"},
    45: {"regiao": "Foz do Iguaçú", "uf": "PR"},
    46: {"regiao": "Pato Branco / Francisco Beltrão", "uf": "PR"},
    47: {"regiao": "Joinville", "uf": "SC"},
    48: {"regiao": "Florianópolis", "uf": "SC"},
    49: {"regiao": "Chapecó", "uf": "SC"},
    51: {"regiao": "Porto Alegre", "uf": "RS"},
    53: {"regiao": "Pelotas", "uf": "RS"},
    54: {"regiao": "Caxias do Sul", "uf": "RS"},
    55: {"regiao": "Santa Maria", "uf": "RS"},
    61: {"regiao": "Brasília", "uf": "DF"},
    62: {"regiao": "Goiânia", "uf": "GO"},
    63: {"regiao": "Palmas", "uf": "TO"},
    64: {"regiao": "Rio Verde", "uf": "GO"},
    65: {"regiao": "Cuiabá", "uf": "MT"},
    66: {"regiao": "Rondonópolis", "uf": "MT"},
    67: {"regiao": "Campo Grande", "uf": "MS"},
    68: {"regiao": "Rio Branco", "uf": "AC"},
    69: {"regiao": "Porto Velho", "uf": "RO"},
    71: {"regiao": "Salvador", "uf": "BA"},
    73: {"regiao": "Ilhéus", "uf": "BA"},
    74: {"regiao": "Juazeiro", "uf": "BA"},
    75: {"regiao": "Feira de Santana", "uf": "BA"},
    77: {"regiao": "Barreiras", "uf": "BA"},
    79: {"regiao": "Aracaju", "uf": "SE"},
    81: {"regiao": "Recife", "uf": "PE"},
    82: {"regiao": "Maceió", "uf": "AL"},
    83: {"regiao": "João Pessoa", "uf": "PB"},
    84: {"regiao": "Natal", "uf": "RN"},
    85: {"regiao": "Fortaleza", "uf": "CE"},
    86: {"regiao": "Teresina", "uf": "PI"},
    87: {"regiao": "Petrolina", "uf": "PE"},
    88: {"regiao": "Juazeiro do Norte", "uf": "CE"},
    89: {"regiao": "Picos", "uf": "PI"},
    91: {"regiao": "Belém", "uf": "PA"},
    92: {"regiao": "Manaus", "uf": "AM"},
    93: {"regiao": "Santarém", "uf": "PA"},
    94: {"regiao": "Marabá", "uf": "PA"},
    95: {"regiao": "Boa Vista", "uf": "RR"},
    96: {"regiao": "Macapá", "uf": "AP"},
    97: {"regiao": "Coari", "uf": "AM"},
    98: {"regiao": "São Luís", "uf": "MA"},
    99: {"regiao": "Imperatriz", "uf": "MA"},
}